# version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pothole_postgres
    environment:
      POSTGRES_DB: potholes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - pothole_network

  # FastAPI Application
  app:
    build: .
    container_name: pothole_app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/potholes
      - SECRET_KEY=your-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    volumes:
      - ./uploads:/app/uploads
      - ./analysis:/app/analysis
      - ./captures:/app/captures
      - ./runs:/app/runs
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - pothole_network

volumes:
  postgres_data:
    driver: local

networks:
  pothole_network:
    driver: bridge